# Generated by Django 4.0.2 on 2023-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_cat', models.CharField(default='FOLDER', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.TextField(default='', max_length=5150)),
                ('main_image', models.ImageField(default='', upload_to='Home/images/folder')),
                ('back_image', models.ImageField(default='', upload_to='Home/images/folder')),
                ('inner_image', models.ImageField(default='', upload_to='Home/images/folder')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
