# Generated by Django 4.0.2 on 2023-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('xL', 'xL'), ('XXL', 'XXL'), ('B4 size', 'B4 size'), ('A4 size', 'A4 size')], default='', max_length=50)),
                ('color', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('addinfo', models.CharField(default='#', max_length=500)),
                ('name', models.CharField(default=0, max_length=12)),
                ('contact', models.CharField(default=0, max_length=12)),
                ('location', models.CharField(default=0, max_length=250)),
                ('image', models.ImageField(default='', upload_to='order')),
            ],
        ),
    ]
