# Generated by Django 4.0.2 on 2023-06-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
