# Generated by Django 4.0.2 on 2023-06-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_cat', models.CharField(default='FOLDER', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='Home/images/product')),
            ],
        ),
    ]
