# Generated by Django 4.0.2 on 2023-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='product_desc',
        ),
        migrations.AddField(
            model_name='folder',
            name='pd1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='folder',
            name='pd2',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='folder',
            name='pd3',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='folder',
            name='pd4',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='folder',
            name='pd5',
            field=models.TextField(default='', max_length=100),
        ),
    ]
