# Generated by Django 4.0.2 on 2023-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_delete_product_remove_folder_product_desc_folder_pd1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='pd1',
            field=models.TextField(default='It is made using high quality PU leather.', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pd2',
            field=models.TextField(default='Paper size is bigger than A4, used to safely keep documents of almost all size.', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pd3',
            field=models.TextField(default='Chain zipper is given to secure everything inside the folder.', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pd4',
            field=models.TextField(default='It is waterproof.', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='pd5',
            field=models.TextField(default='Many compartments to organize documents, cards, id ,pen and many more...', max_length=100),
        ),
    ]
